### ISSUE TITLE
Does it works with Rails 5.2.0?

### ISSUE THREAD

**Issue by gnumarcelo** [hirefire/hirefire-resource#48]
Is this gem supposed to work with Rails 5.2?

hirefire_resource.rb
```
HireFire::Resource.configure do |config|
  config.dyno(:worker) do
    HireFire::Macro::Delayed::Job.queue(mapper: :active_record)
  end
end
```

I made all the configuration but I am still unable to run `http://localhost:3000/hirefire/development/info`. It show the following at my console:

```
» rails s
=> Booting Puma
=> Rails 5.2.0 application starting in development
=> Run `rails server -h` for more startup options
[69695] Puma starting in cluster mode...
[69695] * Version 3.12.0 (ruby 2.5.1-p57), codename: Llamas in Pajamas
[69695] * Min threads: 5, max threads: 5
[69695] * Environment: development
[69695] * Process workers: 2
[69695] * Preloading application
[69695] * Listening on tcp://0.0.0.0:3000
[69695] Use Ctrl-C to stop
[69695] - Worker 0 (pid: 69699) booted, phase: 0
[69695] - Worker 1 (pid: 69700) booted, phase: 0
I, [2019-03-29T17:49:15.924110 #69700]  INFO -- : Started GET "/hirefire/development/info" for 127.0.0.1 at 2019-03-29 17:49:15 -0300
F, [2019-03-29T17:49:16.394343 #69700] FATAL -- :
F, [2019-03-29T17:49:16.394686 #69700] FATAL -- : ActionController::RoutingError (No route matches [GET] "/hirefire/development/info"):
F, [2019-03-29T17:49:16.394909 #69700] FATAL -- :
F, [2019-03-29T17:49:16.395154 #69700] FATAL -- : actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.0) lib/rails/rack/logger.rb:28:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
hirefire-resource (0.7.1) lib/hirefire/middleware.rb:38:in `call'
rack-cors (1.0.2) lib/rack/cors.rb:97:in `call'
railties (5.2.0) lib/rails/engine.rb:524:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
I, [2019-03-29T17:49:16.944156 #69700]  INFO -- :   Rendering /Users/marcelo/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.0/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout
I, [2019-03-29T17:49:17.008265 #69700]  INFO -- :   Rendering /Users/marcelo/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
I, [2019-03-29T17:49:17.011069 #69700]  INFO -- :   Rendered /Users/marcelo/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.0/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (2.2ms)
I, [2019-03-29T17:49:17.082311 #69700]  INFO -- :   Rendered collection of /Users/marcelo/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.0/lib/action_dispatch/middleware/templates/routes/_route.html.erb [34 times] (25.0ms)
I, [2019-03-29T17:49:17.156374 #69700]  INFO -- :   Rendered /Users/marcelo/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.0/lib/action_dispatch/middleware/templates/routes/_table.html.erb (33.8ms)
I, [2019-03-29T17:49:17.202188 #69700]  INFO -- :   Rendering /Users/marcelo/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
I, [2019-03-29T17:49:17.203413 #69700]  INFO -- :   Rendered /Users/marcelo/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (0.9ms)
I, [2019-03-29T17:49:17.203787 #69700]  INFO -- :   Rendered /Users/marcelo/.rvm/gems/ruby-2.5.1/gems/actionpack-5.2.0/lib/action_dispatch/middleware/templates/rescues/routing_error.html.erb within rescues/layout (259.1ms)
```

**Comment by mrrooijen** [comment]
It should work. Could you run `bundle exec rake middleware` to check and see if the `HireFire::Middleware` middleware is listed?

**Comment by gnumarcelo** [comment]
Yes, it is listed:

» bundle exec rake middleware
use Rack::Cors
use HireFire::Middleware
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use ActionDispatch::RequestId
use ActionDispatch::RemoteIp
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use ScoutApm::Middleware
use ScoutApm::Instant::Middleware
use Warden::JWTAuth::Middleware
run MyAppApi::Application.routes

**Comment by mrrooijen** [comment]
Thanks. I've just generated a new Rails app on the latest Ruby and Rails versions and there seem to be no issues. Can you open the Rails Console and run this and tell me the output?

    Rails.application.config.relative_url_root

**Comment by gnumarcelo** [comment]
```
> Rails.application.config.relative_url_root
=> nil
```
ps.: I generated my app using --api, so, it is a `api only` app, do you think this is the problem?

**Comment by mrrooijen** [comment]
I'm not sure. The backtrace suggests that it's going through the middleware, and it's simply falling through to the next middleware because it isn't matching the `/hirefire/development/info` path for some reason.

If that variable returns `nil` then the only thing that could be wrong is `env["PATH_INFO"]`. [This line](https://github.com/hirefire/hirefire-resource/blob/master/lib/hirefire/middleware.rb#L35) is supposed to return `true` when you access the `/hirefire/development/info` url in development. 

Note that it defaults to `/hirefire/development/info` unless you have `HIREFIRE_TOKEN` configured locally. If you have `HIREFIRE_TOKEN` configured locally, e.g. in a `.env` file, then use that token in the URL instead: `/hirefire/$HIREFIRE_TOKEN/info`.

**Comment by gnumarcelo** [comment]
Got it.

Found the problem. My `.env` file was setting the `HIREFIRE_TOKEN` token. I'll close this ticket.

Thanks for the help!

**Comment by mrrooijen** [comment]
No problem!
